spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:servicedesk}
    username: ${DB_USER:servicedesk}
    password: ${DB_PASSWORD:servicedesk}
  flyway:
    schemas: notification
    default-schema: notification

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health
